print("Hello, what is the current day?")
date = input("Thursday")
print("What is your favorite number?")
fave = input("10")
print("What is your favorite color?")
color = input("Red")
print("How many countries have you visited?")
countries = input("12")
print("Please give me a number between 1 and 100")
number1 = input("10: ")
print("Please give me another number between 1 and 100")
number2 = input("99: ")
print("The sum of the last 2 numbers is 109.")

